QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
POINTING_DEVICE_ENABLE = yes

COMBO_ENABLE = yes
NKRO_ENABLE = yes
ENCODER_MAP_ENABLE = yes